### ISSUE TITLE
Dead links cause layout crash

### ISSUE THREAD

**Issue by sxzz** [userquin/vite-pwa-vitepress-integration#22]
- Visit https://vite-pwa-org.netlify.app/not-found
- Click `Get Started`
- <img width="1423" alt="image" src="https://github.com/vite-pwa/vitepress/assets/6481596/6df0e01f-0125-449d-9404-0d08735c7ff6">

So do [Vue Macros](https://vue-macros.dev/), [VueUse](https://vueuse.org/)

**Comment by userquin** [comment]
@sxzz 

On local works, running `nr preview` in pwa docs repo (VP build + preview),  VP shows the not found page, 404.html, since the server is returning 404 status code.

The problem is the SPA configuration in Netlify, any request to a missing page will fallback to index.html with status code 200 (without redirection, just forwarding content). The SW will intercept the request and fallback to index.html since that page isn't in the SW precache manifest (there is an hydration missmatch error in the console).

**Comment by userquin** [comment]
Check response in netlify docs using `/xxx` in home page (first screenshot) and the same request in local (last screenshot).

![imagen](https://github.com/vite-pwa/vitepress/assets/6311119/08f276fd-afbc-4e47-9450-78da602d43a7)

![imagen](https://github.com/vite-pwa/vitepress/assets/6311119/8c6f588a-5de4-4480-b2cb-d22dbf895aee)

**Comment by userquin** [comment]
and the hydration error:

![imagen](https://github.com/vite-pwa/vitepress/assets/6311119/c1e42cd2-b4b2-4b8d-915c-552b5c57d3e5)

**Comment by userquin** [comment]
upps, something wrong on my local, missing sw....

**Comment by userquin** [comment]
same behavior in local and Netlify, `/xxx.html` from sw with fallback content (`/`)
